### ISSUE TITLE
Flash lors de certaine action sur le menu

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/Copyright-teamreda#2]
Quand je clique sur certains items à certains moment, on remarque une sorte de "flash" ou de clignotement.

Bug présent sur Internet Explorer, Firefox et Chrome.

**Comment by mistraloz** [comment]
J'ai pushé une modif. Le bug venait d'une de mes modifs qui permets d'afficher la bonne #ancre dans la barre d'adresse. Sauf qu'au click sur un élément de menu, il y a une animation qui dure 1,5sec. Le fait de placer l'ancre dans l'url entrait en conflit avec l'animation. 

J'ai donc modifié pour que la modification dans la barre de titre n'intervienne qu'à la fin de l'animation.

**Comment by Farocs** [comment]
J'ai l'impression que ca bug toujours, tu avais modifié que l'agency.css ?

**Comment by Farocs** [comment]
J'ai rien dit, mauvais upload et mauvaise lecture (tu avais naturellement modifé l'agency.js, pas le CSS).

Problème corrigé :)
